-- phpMyAdmin SQL Dump
-- version 4.1.14
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: Apr 14, 2015 at 07:29 AM
-- Server version: 5.6.17
-- PHP Version: 5.5.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `scrapedcourse`
--

-- --------------------------------------------------------

--
-- Table structure for table `education`
--

CREATE TABLE IF NOT EXISTS `education` (
  `id` int(5) NOT NULL AUTO_INCREMENT,
  `title` text CHARACTER SET latin1 NOT NULL,
  `description` text CHARACTER SET latin1 NOT NULL,
  `lesson_link` text CHARACTER SET latin1 NOT NULL,
  `lesson_image` text CHARACTER SET latin1 NOT NULL,
  `category` varchar(200) CHARACTER SET latin1 NOT NULL,
  `student_grades` set('1','2','3','4','5','6','7','8','9','10','11','12','k') CHARACTER SET latin1 NOT NULL,
  `author` text CHARACTER SET latin1 NOT NULL,
  `content_type` text CHARACTER SET latin1 NOT NULL,
  `time_scraped` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=132 ;

--
-- Dumping data for table `education`
--

INSERT INTO `education` (`id`, `title`, `description`, `lesson_link`, `lesson_image`, `category`, `student_grades`, `author`, `content_type`, `time_scraped`) VALUES
(1, 'Acid-Base Solutions', 'How do strong and weak acids differ? Use lab tools on your computer to find out! Dip the paper or the probe into solution to measure the pH, or put in the electrodes to measure the conductivity. Then see how concentration and strength affect pH. Can a weak acid solution have the same pH as a strong acid solution?', 'https://phet.colorado.edu/en/simulation/acid-base-solutions', 'https://phet.colorado.edu/sims/acid-base-solutions/acid-base-solutions-thumbnail.png', 'Chemistry-General Chemistry', '9,10,11,12', 'Kelly Lancaster (lead),Chris Malley (developer),Patricia Loeblein,Robert Parson,Kathy Perkins', 'iPad/Tablet,Chromebook,Run Now!,Download,Embed,Run in HTML5', '2015-04-13 22:24:56'),
(2, 'Alpha Decay', 'Watch alpha particles escape from a polonium nucleus, causing radioactive alpha decay. See how random decay times relate to the half life.', 'https://phet.colorado.edu/en/simulation/alpha-decay', 'https://phet.colorado.edu/sims/nuclear-physics/alpha-decay-thumbnail.png', 'Physics-Quantum Phenomena,Physics-Light & Radiation,Chemistry-General Chemistry', '6,7,8,9,10,11,12', 'Wendy Adams,John Blanco (developer),Ron LeMaster (developer),Sam McKagan,Kathy Perkins,Noah Podolefsky,Carl Wieman,Interviewer: Wendy Adams,Interviewer: Danielle Harlow', 'Run Now!,Download,Embed', '2015-04-13 22:24:56'),
(3, 'Area Builder', 'Create your own shapes using colorful blocks and explore the relationship between perimeter and area. Compare the area and perimeter of two shapes side-by-side. Challenge yourself in the game screen to build shapes or find the area of funky figures. Try to collect lots of stars!', 'https://phet.colorado.edu/en/simulation/area-builder', 'https://phet.colorado.edu/sims/html/area-builder/1.0.0/area-builder-128.png', 'Math', '1,2,3,4,5,6,7,8,9,10,11,12,k', 'Karina K.R. Hensberry (lead),John Blanco (developer),Bryce Gruneich,Amanda McGarry,Ariel Paul,Kathy Perkins,Beth Stade', 'iPad/Tablet,Chromebook,Run Now!,Download,Embed', '2015-04-13 22:24:56'),
(4, 'Arithmetic', 'Remember your multiplication tables? ... me neither. Brush up on your multiplication, division, and factoring skills with this exciting game. No calculators allowed!', 'https://phet.colorado.edu/en/simulation/arithmetic', 'https://phet.colorado.edu/sims/arithmetic/arithmetic-thumbnail.jpg', 'Math', '1,2,3,4,5,6,7,8,k', 'Michael Dubson (developer/lead),Trish Loeblein', 'Chromebook,Download,Embed,Run Now!', '2015-04-13 22:24:57'),
(5, 'Atomic Interactions', 'Explore the interactions between various combinations of two atoms. Turn on the force arrows to see either the total force acting on the atoms or the individual attractive and repulsive forces. Try the "Adjustable Attraction" atom to see how changing the parameters affects the interaction.', 'https://phet.colorado.edu/en/simulation/atomic-interactions', 'https://phet.colorado.edu/sims/states-of-matter/atomic-interactions-thumbnail.png', 'Chemistry-General Chemistry', '9,10,11,12', 'Wendy Adams,John Blanco (developer),Kathy Perkins,Noah Podolefsky,Carl Wieman,Jack Barbera (interviews),Kelly Lancaster (interviews)', 'Run Now!,Download,Embed', '2015-04-13 22:24:57'),
(6, 'Balancing Act', 'Play with objects on a teeter totter to learn about balance. Test what you''ve learned by trying the Balance Challenge game.', 'https://phet.colorado.edu/en/simulation/balancing-act', 'https://phet.colorado.edu/sims/balance-and-torque/balancing-act-thumbnail.png', 'Physics-Motion,Math', '1,2,3,4,5,6,7,8,k', 'Kathy Perkins (co-lead),John Blanco (co-lead, developer),Michael Dubson,Trish Loeblein,Ariel Paul', 'iPad/Tablet,Chromebook,Run Now!,Download,Embed,Run in HTML5', '2015-04-13 22:24:57'),
(7, 'Balancing Chemical Equations', 'How do you know if a chemical equation is balanced? What can you change to balance an equation? Play a game to test your ideas!', 'https://phet.colorado.edu/en/simulation/balancing-chemical-equations', 'https://phet.colorado.edu/sims/balancing-chemical-equations/balancing-chemical-equations-thumbnail.png', 'Chemistry-General Chemistry', '6,7,8,9,10,11,12', 'Kelly Lancaster (lead),Chris Malley (developer),Patricia Loeblein,Emily Moore,Robert Parson,Kathy Perkins', 'iPad/Tablet,Chromebook,Run Now!,Download,Embed,Run in HTML5', '2015-04-13 22:24:57'),
(8, 'Balloons & Buoyancy', 'Experiment with a helium balloon, a hot air balloon, or a rigid sphere filled with different gases. Discover what makes some balloons float and others sink.', 'https://phet.colorado.edu/en/simulation/balloons-and-buoyancy', 'https://phet.colorado.edu/sims/ideal-gas/balloons-and-buoyancy-thumbnail.png', 'Physics-Work, Energy & Power,Physics-Heat & Thermo,Chemistry-General Chemistry,Earth Science', '6,7,8,9,10,11,12', 'Ron LeMaster (developer),Kathy Perkins,Carl Wieman,Interviewer: Danielle Harlow', 'Run Now!,Download,Embed', '2015-04-13 22:24:59'),
(9, 'Balloons and Static Electricity', 'Why does a balloon stick to your sweater? Rub a balloon on a sweater, then let go of the balloon and it flies over and sticks to the sweater. View the charges in the sweater, balloons, and the wall.', 'https://phet.colorado.edu/en/simulation/balloons', 'https://phet.colorado.edu/sims/balloons/balloons-thumbnail.png', 'Physics-Electricity, Magnets & Circuits,Biology,Chemistry-General Chemistry,Earth Science', '1,2,3,4,5,6,7,8,9,10,11,12,k', 'Sam Reid (developer/lead),Interviewer: Wendy Adams', 'iPad/Tablet,Chromebook,Run Now!,Download,Embed,Run in HTML5', '2015-04-13 22:24:59'),
(10, 'Band Structure', 'Explore the origin of energy bands in crystals of atoms. The structure of these bands determines how materials conduct electricity.', 'https://phet.colorado.edu/en/simulation/band-structure', 'https://phet.colorado.edu/sims/bound-states/band-structure-thumbnail.png', 'Physics-Quantum Phenomena', '', 'Chris Malley (developer),Sam McKagan (lead),Kathy Perkins,Carl Wieman,Interviewer: Sam McKagan', 'Run Now!,Download,Embed', '2015-04-13 22:25:00'),
(11, 'Battery-Resistor Circuit', 'Look inside a resistor to see how it works. Increase the battery voltage to make more electrons flow though the resistor. Increase the resistance to block the flow of electrons. Watch the current and resistor temperature change.', 'https://phet.colorado.edu/en/simulation/battery-resistor-circuit', 'https://phet.colorado.edu/sims/battery-resistor-circuit/battery-resistor-circuit-thumbnail.png', 'Physics-Electricity, Magnets & Circuits', '6,7,8,9,10,11,12', 'Sam Reid (developer),Carl Wieman', 'Run Now!,Download,Embed', '2015-04-13 22:25:00'),
(12, 'Battery Voltage', 'Look inside a battery to see how it works. Select the battery voltage and little stick figures move charges from one end of the battery to the other. A voltmeter tells you the resulting battery voltage.', 'https://phet.colorado.edu/en/simulation/battery-voltage', 'https://phet.colorado.edu/sims/battery-voltage/battery-voltage-thumbnail.png', 'Physics-Electricity, Magnets & Circuits', '6,7,8,9,10,11,12', 'Sam Reid (Developer),Carl Wieman', 'Run Now!,Download,Embed', '2015-04-13 22:25:01'),
(13, 'Beer''s Law Lab', '“The thicker the glass, the darker the brew, the less the light that passes through.” Make colorful concentrated and dilute solutions and explore how much light they absorb and transmit using a virtual spectrophotometer!', 'https://phet.colorado.edu/en/simulation/beers-law-lab', 'https://phet.colorado.edu/sims/beers-law-lab/beers-law-lab-thumbnail.png', 'Chemistry-General Chemistry', '9,10,11,12', 'Julia Chamberlain (lead),Chris Malley (developer),Kelly Lancaster,Emily B. Moore,Kathy Perkins', 'iPad/Tablet,Chromebook,Run Now!,Download,Embed,Run in HTML5', '2015-04-13 22:25:01'),
(14, 'Bending Light', 'Explore bending of light between two media with different indices of refraction. See how changing from air to water to glass changes the bending angle. Play with prisms of different shapes and make rainbows.', 'https://phet.colorado.edu/en/simulation/bending-light', 'https://phet.colorado.edu/sims/bending-light/bending-light-thumbnail.png', 'Physics-Light & Radiation', '1,2,3,4,5,6,7,8,9,10,11,12,k', 'Noah Podolefsky (lead),Kathy Perkins,Trish Loeblein,Emily Moore (interviews),Sam Reid (developer)', 'Run Now!,Download,Embed', '2015-04-13 22:25:01'),
(15, 'Beta Decay', 'Watch beta decay occur for a collection of nuclei or for an individual nucleus.', 'https://phet.colorado.edu/en/simulation/beta-decay', 'https://phet.colorado.edu/sims/nuclear-physics/beta-decay-thumbnail.png', 'Physics-Quantum Phenomena,Physics-Light & Radiation,Chemistry-General Chemistry', '9,10,11,12', 'Wendy Adams,John Blanco (developer),Kathy Perkins,Noah Podolefsky,Carl Wieman,Interviewer: Noah Podolefsky', 'Run Now!,Download,Embed', '2015-04-13 22:25:01'),
(16, 'Blackbody Spectrum', 'How does the blackbody spectrum of the sun compare to visible light? Learn about the blackbody spectrum of the sun, a light bulb, an oven, and the earth. Adjust the temperature to see the wavelength and intensity of the spectrum change. View the color of the peak of the spectral curve.', 'https://phet.colorado.edu/en/simulation/blackbody-spectrum', 'https://phet.colorado.edu/sims/blackbody-spectrum/blackbody-spectrum-thumbnail.jpg', 'Physics-Heat & Thermo,Physics-Quantum Phenomena,Physics-Light & Radiation,Biology,Chemistry-General Chemistry,Earth Science', '6,7,8,9,10,11,12', 'Michael Dubson (developer/lead),Kathy Perkins,Interviewer: Wendy Adams', 'Chromebook,Download,Embed,Run Now!', '2015-04-13 22:25:02'),
(17, 'Build a Fraction', 'Build fractions from shapes and numbers to earn stars in this fractions game or explore in the Fractions Lab. Challenge yourself on any level you like. Try to collect lots of stars!', 'https://phet.colorado.edu/en/simulation/build-a-fraction', 'https://phet.colorado.edu/sims/fractions/build-a-fraction-thumbnail.png', 'Math', '1,2,3,4,5,6,7,8,9,10,11,12,k', 'Ariel Paul (lead designer),Sam Reid (lead developer),Kathy Perkins,Trish Loeblein,Karina Hensberry,Mike Dubson', 'Run Now!,Download,Embed', '2015-04-13 22:25:02'),
(18, 'Build a Molecule', 'Starting from atoms, see how many molecules you can build. Collect your molecules and see them in 3D!', 'https://phet.colorado.edu/en/simulation/build-a-molecule', 'https://phet.colorado.edu/sims/build-a-molecule/build-a-molecule-thumbnail.png', 'Chemistry-General Chemistry', '6,7,8,9,10,11,12', 'Emily Moore (Lead),Jonathan Olson (Lead Developer),John Blanco (Developer),Sam Reid (Developer),Kelly Lancaster,Kathy Perkins,Christine Denison', 'Run Now!,Download,Embed', '2015-04-13 22:25:03'),
(19, 'Build an Atom', 'Build an atom out of protons, neutrons, and electrons, and see how the element, charge, and mass change. Then play a game to test your ideas!', 'https://phet.colorado.edu/en/simulation/build-an-atom', 'https://phet.colorado.edu/sims/build-an-atom/build-an-atom-thumbnail.png', 'Chemistry-General Chemistry', '1,2,3,4,5,6,7,8,9,10,11,12,k', 'Kelly Lancaster (lead),John Blanco (developer),Sam Reid (developer),Jack Barbera,Suzanne Brahmia,Patricia Loeblein,Robert Parson,Kathy Perkins', 'iPad/Tablet,Chromebook,Run Now!,Download,Embed,Run in HTML5', '2015-04-13 22:25:03'),
(20, 'Buoyancy', 'When will objects float and when will they sink? Learn how buoyancy works with blocks. Arrows show the applied forces, and you can modify the properties of the blocks and the fluid.', 'https://phet.colorado.edu/en/simulation/buoyancy', 'https://phet.colorado.edu/sims/density-and-buoyancy/buoyancy-thumbnail.jpg', 'Physics-Motion', '6,7,8,9,10,11,12', 'Wendy Adams,Kelly Lancaster (lead),Trish Loeblein,Chris Malley,Jonathan Olson (developer),Archie Paulson,Kathy Perkins,Noah Podolefsky (interviewer),Sam Reid (developer),Carl Wieman', 'Chromebook,Download,Embed,Run Now!', '2015-04-13 22:25:04'),
(21, 'Calculus Grapher', 'Draw a graph of any function and see graphs of its derivative and integral. Don''t forget to use the magnify/demagnify controls on the y-axis to adjust the scale.', 'https://phet.colorado.edu/en/simulation/calculus-grapher', 'https://phet.colorado.edu/sims/calculus-grapher/calculus-grapher-thumbnail.png', 'Physics-Motion,Math', '9,10,11,12', 'Michael Dubson (lead),Trish Loeblein', 'Chromebook,Download,Embed,Run Now!', '2015-04-13 22:25:04'),
(22, 'Capacitor Lab', 'Explore how a capacitor works! Change the size of the plates and add a dielectric to see how it affects capacitance. Change the voltage and see charges built up on the plates. Shows the electric field in the capacitor. Measure voltage and electric field.', 'https://phet.colorado.edu/en/simulation/capacitor-lab', 'https://phet.colorado.edu/sims/capacitor-lab/capacitor-lab-thumbnail.png', 'Physics-Electricity, Magnets & Circuits', '6,7,8,9,10,11,12', 'Noah Podolefsky (lead),Chris Malley (developer),Kathy Perkins,Mike Dubson', 'Run Now!,Download,Embed', '2015-04-13 22:25:04'),
(23, 'Charges and Fields', 'Move point charges around on the playing field and then view the electric field, voltages, equipotential lines, and more. It''s colorful, it''s dynamic, it''s free.', 'https://phet.colorado.edu/en/simulation/charges-and-fields', 'https://phet.colorado.edu/sims/charges-and-fields/charges-and-fields-thumbnail.jpg', 'Physics-Electricity, Magnets & Circuits', '9,10,11,12', 'Michael Dubson (developer/lead)', 'Chromebook,Download,Embed,Run Now!', '2015-04-13 22:25:04'),
(24, 'Circuit Construction Kit (AC+DC)', 'This new version of the CCK adds capacitors, inductors and AC voltage sources to your toolbox! Now you can graph the current and voltage as a function of time.', 'https://phet.colorado.edu/en/simulation/circuit-construction-kit-ac', 'https://phet.colorado.edu/sims/circuit-construction-kit/circuit-construction-kit-ac-thumbnail.png', 'Physics-Electricity, Magnets & Circuits', '6,7,8,9,10,11,12', 'Michael Dubson,Kathy Perkins,Sam Reid (developer/lead),Carl Wieman', 'Run Now!,Download,Embed', '2015-04-13 22:25:05'),
(25, 'Circuit Construction Kit (AC+DC), Virtual Lab', 'Build circuits with capacitors, inductors, resistors and AC or DC voltage sources, and inspect them using lab instruments such as voltmeters and ammeters.', 'https://phet.colorado.edu/en/simulation/circuit-construction-kit-ac-virtual-lab', 'https://phet.colorado.edu/sims/circuit-construction-kit/circuit-construction-kit-ac-virtual-lab-thumbnail.png', 'Physics-Electricity, Magnets & Circuits', '6,7,8,9,10,11,12', 'Michael Dubson,Kathy Perkins,Sam Reid (developer/lead),Carl Wieman', 'Run Now!,Download,Embed', '2015-04-13 22:25:05'),
(26, 'Circuit Construction Kit (DC Only)', 'An electronics kit in your computer! Build circuits with resistors, light bulbs, batteries, and switches. Take measurements with the realistic ammeter and voltmeter. View the circuit as a schematic diagram, or switch to a life-like view.', 'https://phet.colorado.edu/en/simulation/circuit-construction-kit-dc', 'https://phet.colorado.edu/sims/circuit-construction-kit/circuit-construction-kit-dc-thumbnail.png', 'Physics-Electricity, Magnets & Circuits', '1,2,3,4,5,6,7,8,9,10,11,12,k', 'Wendy Adams,Michael Dubson,Kathy Perkins,Sam Reid (developer/lead),Carl Wieman,Interviewer: Wendy Adams', 'Run Now!,Download,Embed', '2015-04-13 22:25:05'),
(27, 'Circuit Construction Kit (DC Only), Virtual Lab', 'Build circuits with resistors, light bulbs, batteries, and switches and take measurements with laboratory equipment like the realistic ammeter and voltmeter.', 'https://phet.colorado.edu/en/simulation/circuit-construction-kit-dc-virtual-lab', 'https://phet.colorado.edu/sims/circuit-construction-kit/circuit-construction-kit-dc-virtual-lab-thumbnail.png', 'Physics-Electricity, Magnets & Circuits', '1,2,3,4,5,6,7,8,9,10,11,12,k', 'Wendy Adams,Michael Dubson,Kathy Perkins,Sam Reid (developer/lead),Carl Wieman,Interviewer: Wendy Adams', 'Run Now!,Download,Embed', '2015-04-13 22:25:06'),
(28, 'Collision Lab', 'Use an air hockey table to investigate simple collisions in 1D and more complex collisions in 2D. Experiment with the number of discs, masses, and initial conditions. Vary the elasticity and see how the total momentum and kinetic energy changes during collisions.', 'https://phet.colorado.edu/en/simulation/collision-lab', 'https://phet.colorado.edu/sims/collision-lab/collision-lab-thumbnail.png', 'Physics-Motion', '6,7,8,9,10,11,12', 'Mike Dubson (design + development),Trish Loeblein,Kathy Perkins,Mindy Gratny (interviews),Jon Olson,Sam Reid,Ariel Paul (interviews)', 'Chromebook,Download,Embed,Run Now!', '2015-04-13 22:25:06'),
(29, 'Color Vision', 'Make a whole rainbow by mixing red, green, and blue light. Change the wavelength of a monochromatic beam or filter white light. View the light as a solid beam, or see the individual photons.', 'https://phet.colorado.edu/en/simulation/color-vision', 'https://phet.colorado.edu/sims/color-vision/color-vision-thumbnail.png', 'Physics-Light & Radiation,Biology', '1,2,3,4,5,6,7,8,9,10,11,12,k', 'Ron LeMaster (developer),Chris Malley (developer),Kathy Perkins,Carl Wieman,Interviewer: Wendy Adams,Interviewer: Danielle Harlow', 'iPad/Tablet,Chromebook,Run Now!,Download,Embed,Run in HTML5', '2015-04-13 22:25:06'),
(30, 'Concentration', 'Watch your solution change color as you mix chemicals with water. Then check molarity with the concentration meter. What are all the ways you can change the concentration of your solution? Switch solutes to compare different chemicals and find out how concentrated you can go before you hit saturation!', 'https://phet.colorado.edu/en/simulation/concentration', 'https://phet.colorado.edu/sims/beers-law-lab/concentration-thumbnail.png', 'Chemistry-General Chemistry', '1,2,3,4,5,9,10,11,12,k', 'Julia Chamberlain (lead),Chris Malley (developer),Kelly Lancaster,Emily B. Moore,Kathy Perkins', 'iPad/Tablet,Chromebook,Run Now!,Download,Embed,Run in HTML5', '2015-04-13 22:25:06'),
(31, 'Conductivity', 'Experiment with conductivity in metals, plastics and photoconductors. See why metals conduct and plastics don''t, and why some materials conduct only when you shine a flashlight on them.', 'https://phet.colorado.edu/en/simulation/conductivity', 'https://phet.colorado.edu/sims/conductivity/conductivity-thumbnail.png', 'Physics-Quantum Phenomena,Physics-Electricity, Magnets & Circuits,Chemistry-Quantum Chemistry', '9,10,11,12', 'Sam McKagan,Kathy Perkins,Sam Reid (developer),Carl Wieman,Interviewer: Wendy Adams', 'Run Now!,Download,Embed', '2015-04-13 22:25:07'),
(32, 'Curve Fitting', 'With your mouse, drag data points and their error bars, and watch the best-fit polynomial curve update instantly. You choose the type of fit: linear, quadratic, cubic, or quartic. The reduced chi-square statistic shows you when the fit is good. Or you can try to find the best fit by manually adjusting fit parameters.', 'https://phet.colorado.edu/en/simulation/curve-fitting', 'https://phet.colorado.edu/sims/curve-fitting/curve-fitting-thumbnail.jpg', 'Biology,Math', '6,7,8,9,10,11,12', 'Michael Dubson (developer/lead),Trish Loeblein', 'Chromebook,Download,Embed,Run Now!', '2015-04-13 22:25:07'),
(33, 'Davisson-Germer: Electron Diffraction', 'Simulate the original experiment that proved that electrons can behave as waves. Watch electrons diffract off a crystal of atoms, interfering with themselves to create peaks and troughs of probability.', 'https://phet.colorado.edu/en/simulation/davisson-germer', 'https://phet.colorado.edu/sims/quantum-wave-interference/davisson-germer-thumbnail.png', 'Physics-Quantum Phenomena,Chemistry-Quantum Chemistry', '', 'Sam McKagan (lead),Kathy Perkins,Sam Reid (developer),Carl Wieman,Interviewer: Sam McKagan', 'Run Now!,Download,Embed', '2015-04-13 22:25:08'),
(34, 'Density', 'Why do objects like wood float in water? Does it depend on size? Create a custom object to explore the effects of mass and volume on density. Can you discover the relationship? Use the scale to measure the mass of an object, then hold the object under water to measure its volume. Can you identify all the mystery objects?', 'https://phet.colorado.edu/en/simulation/density', 'https://phet.colorado.edu/sims/density-and-buoyancy/density-thumbnail.jpg', 'Biology,Chemistry-General Chemistry', '1,2,3,4,5,6,7,8,9,10,11,12,k', 'Wendy Adams,Kelly Lancaster (lead),Trish Loeblein,Chris Malley,Jonathan Olson (developer),Archie Paulson,Kathy Perkins,Noah Podolefsky,Sam Reid (developer),Carl Wieman', 'Chromebook,Download,Embed,Run Now!', '2015-04-13 22:25:08'),
(35, 'Double Wells and Covalent Bonds', 'Explore tunneling splitting in double well potentials. This classic problem describes many physical systems, including covalent bonds, Josephson junctions, and two-state systems such as spin 1/2 particles and ammonia molecules.', 'https://phet.colorado.edu/en/simulation/covalent-bonds', 'https://phet.colorado.edu/sims/bound-states/covalent-bonds-thumbnail.png', 'Physics-Quantum Phenomena,Chemistry-Quantum Chemistry', '', 'Chris Malley (developer),Sam McKagan (lead),Kathy Perkins,Carl Wieman,Interviewer: Sam McKagan', 'Run Now!,Download,Embed', '2015-04-13 22:25:08'),
(36, 'Eating & Exercise', 'How many calories are in your favorite foods? How much exercise would you have to do to burn off these calories? What is the relationship between calories and weight? Explore these issues by choosing diet and exercise and keeping an eye on your weight.', 'https://phet.colorado.edu/en/simulation/eating-and-exercise', 'https://phet.colorado.edu/sims/eating-and-exercise/eating-and-exercise-thumbnail.png', 'Biology', '1,2,3,4,5,6,7,8,9,10,11,12,k', 'Wendy Adams,Noah Podolefsky,Kathy Perkins,Kate Semsar,Franny Benay,Sam Reid (developer)', 'Run Now!,Download,Embed', '2015-04-13 22:25:08'),
(37, 'Electric Field Hockey', 'Play hockey with electric charges. Place charges on the ice, then hit start to try to get the puck in the goal. View the electric field. Trace the puck''s motion. Make the game harder by placing walls in front of the goal. This is a clone of the popular simulation of the same name marketed by Physics Academic Software and written by Prof. Ruth Chabay of the Dept of Physics at North Carolina State University.', 'https://phet.colorado.edu/en/simulation/electric-hockey', 'https://phet.colorado.edu/sims/electric-hockey/electric-hockey-thumbnail.png', 'Physics-Electricity, Magnets & Circuits', '1,2,3,4,5,6,7,8,9,10,11,12,k', 'Michael Dubson (developer/lead),Sam Reid (developer),Interviewer: Wendy Adams,Interviewer: Danielle Harlow', 'Run Now!,Download,Embed', '2015-04-13 22:25:11'),
(38, 'Electric Field of Dreams', 'Play ball! Add charges to the Field of Dreams and see how they react to the electric field. Turn on a background electric field and adjust the direction and magnitude. (Kevin Costner not included).', 'https://phet.colorado.edu/en/simulation/efield', 'https://phet.colorado.edu/sims/efield/efield-thumbnail.png', 'Physics-Electricity, Magnets & Circuits', '9,10,11,12', 'Sam Reid (developer),Carl Wieman', 'Run Now!,Download,Embed', '2015-04-13 22:25:12'),
(39, 'Energy Forms and Changes', 'Explore how heating and cooling iron, brick, and water adds or removes energy. See how energy is transferred between objects. Build your own system, with energy sources, changers, and users. Track and visualize how energy flows and changes through your system.', 'https://phet.colorado.edu/en/simulation/energy-forms-and-changes', 'https://phet.colorado.edu/sims/energy-forms-and-changes/energy-forms-and-changes-thumbnail.png', 'Physics-Work, Energy & Power,Physics-Heat & Thermo,Chemistry-General Chemistry', '1,2,3,4,5,6,7,8,9,10,11,12,k', 'Noah Podolefsky (lead designer, interviewer),John Blanco (developer),Ariel Paul,Emily Moore,Kathy Perkins,Trish Loeblein', 'Run Now!,Download,Embed', '2015-04-13 22:25:12'),
(40, 'Energy Skate Park', 'Learn about conservation of energy with a skater dude! Build tracks, ramps and jumps for the skater and view the kinetic energy, potential energy and friction as he moves. You can also take the skater to different planets or even space!', 'https://phet.colorado.edu/en/simulation/energy-skate-park', 'https://phet.colorado.edu/sims/energy-skate-park/energy-skate-park-thumbnail.png', 'Physics-Motion,Physics-Work, Energy & Power', '1,2,3,4,5,6,7,8,9,10,11,12,k', 'Wendy Adams,Michael Dubson,Trish Loeblein,Kathy Perkins,Sam Reid (developer/lead),Carl Wieman,Interviewer: Danielle Harlow', 'Run Now!,Download,Embed', '2015-04-13 22:25:13'),
(41, 'Energy Skate Park: Basics', 'Learn about conservation of energy with a skater dude! Explore different tracks and view the kinetic energy, potential energy and friction as he moves. Build your own tracks, ramps and jumps for the skater.', 'https://phet.colorado.edu/en/simulation/energy-skate-park-basics', 'https://phet.colorado.edu/sims/energy-skate-park/energy-skate-park-basics-thumbnail.png', 'Physics-Motion,Physics-Work, Energy & Power', '1,2,3,4,5,6,7,8,k', 'Lead designer: Noah Podolefsky,Katherine Perkins,Emily B Moore,Ariel Paul,Trish Loeblein,Developer: Sam Reid,Interviewers: Noah Podolefsky & Ariel Paul', 'iPad/Tablet,Chromebook,Run Now!,Download,Embed,Run in HTML5', '2015-04-13 22:25:13'),
(42, 'Equation Grapher', 'Learn about graphing polynomials. The shape of the curve changes as the constants are adjusted. View the curves for the individual terms (e.g. y=bx ) to see how they add to generate the polynomial curve.', 'https://phet.colorado.edu/en/simulation/equation-grapher', 'https://phet.colorado.edu/sims/equation-grapher/equation-grapher-thumbnail.jpg', 'Math', '6,7,8,9,10,11,12', 'Michael Dubson (developer/lead),Trish Loeblein,Interviewer: Mindy Gratny', 'Chromebook,Download,Embed,Run Now!', '2015-04-13 22:25:13'),
(43, 'Estimation', 'Explore size estimation in one, two and three dimensions! Multiple levels of difficulty allow for progressive skill improvement.', 'https://phet.colorado.edu/en/simulation/estimation', 'https://phet.colorado.edu/sims/estimation/estimation-thumbnail.jpg', 'Math', '1,2,3,4,5,6,7,8,9,10,11,12,k', 'Michael Dubson (developer/lead),Interviewer: Mindy Gratny', 'Chromebook,Download,Embed,Run Now!', '2015-04-13 22:25:13'),
(44, 'Faraday''s Electromagnetic Lab', 'Play with a bar magnet and coils to learn about Faraday''s law. Move a bar magnet near one or two coils to make a light bulb glow. View the magnetic field lines. A meter shows the direction and magnitude of the current. View the magnetic field lines or use a meter to show the direction and magnitude of the current. You can also play with electromagnets, generators and transformers!', 'https://phet.colorado.edu/en/simulation/faraday', 'https://phet.colorado.edu/sims/faraday/faraday-thumbnail.png', 'Physics-Work, Energy & Power,Physics-Electricity, Magnets & Circuits', '1,2,3,4,5,6,7,8,9,10,11,12,k', 'Michael Dubson,Chris Malley (developer),Kathy Perkins,Carl Wieman,Interviewer: Danielle Harlow,Interviewer: Archie Paulson', 'Run Now!,Download,Embed', '2015-04-13 22:25:14'),
(45, 'Faraday''s Law', 'Light a light bulb by waving a magnet. This demonstration of Faraday''s Law shows you how to reduce your power bill at the expense of your grocery bill.', 'https://phet.colorado.edu/en/simulation/faradays-law', 'https://phet.colorado.edu/sims/faradays-law/faradays-law-thumbnail.png', 'Physics-Electricity, Magnets & Circuits', '6,7,8,9,10,11,12', 'Michael Dubson (developer/lead),Trish Loeblein', 'iPad/Tablet,Chromebook,Download,Embed,Run in HTML5,Run Now!', '2015-04-13 22:25:14'),
(46, 'Fluid Pressure and Flow', 'Explore pressure in the atmosphere and underwater. Reshape a pipe to see how it changes fluid flow speed. Experiment with a leaky water tower to see how the height and water level determine the water trajectory.', 'https://phet.colorado.edu/en/simulation/fluid-pressure-and-flow', 'https://phet.colorado.edu/sims/fluid-pressure-and-flow/fluid-pressure-and-flow-thumbnail.png', 'Physics-Motion,Earth Science', '9,10,11,12', 'Sam Reid (lead designer/developer),Noah Podolefsky,Ariel Paul,Trish Loeblein,Kathy Perkins', 'Run Now!,Download,Embed', '2015-04-13 22:25:16'),
(47, 'Forces and Motion', 'Explore the forces at work when you try to push a filing cabinet. Create an applied force and see the resulting friction force and total force acting on the cabinet. Charts show the forces, position, velocity, and acceleration vs. time. View a Free Body Diagram of all the forces (including gravitational and normal forces).', 'https://phet.colorado.edu/en/simulation/forces-and-motion', 'https://phet.colorado.edu/sims/motion-series/forces-and-motion-thumbnail.png', 'Physics-Motion', '6,7,8,9,10,11,12', 'Sam Reid (developer),Noah Podelefsky (lead designer),Trish Loeblein,Kathy Perkins', 'Run Now!,Download,Embed', '2015-04-13 22:25:17'),
(48, 'Forces and Motion: Basics', 'Explore the forces at work when pulling against a cart,and pushing a refrigerator, crate, or person. Create an applied force and see how it makes objects move. Change friction and see how it affects the motion of objects.', 'https://phet.colorado.edu/en/simulation/forces-and-motion-basics', 'https://phet.colorado.edu/sims/forces-and-motion-basics/forces-and-motion-basics-thumbnail.png', 'Physics-Motion', '1,2,3,4,5,6,7,8,9,10,11,12,k', 'Noah Podolefsky (lead designer),Sam Reid (lead developer),Ariel Paul,Kathy Perkins,Trish Loeblein', 'iPad/Tablet,Chromebook,Run Now!,Download,Embed,Run in HTML5', '2015-04-13 22:25:17'),
(49, 'Forces in 1 Dimension', 'Explore the forces at work when you try to push a filing cabinet. Create an applied force and see the resulting friction force and total force acting on the cabinet. Charts show the forces, position, velocity, and acceleration vs. time. View a Free Body Diagram of all the forces (including gravitational and normal forces).', 'https://phet.colorado.edu/en/simulation/forces-1d', 'https://phet.colorado.edu/sims/forces-1d/forces-1d-thumbnail.png', 'Physics-Motion', '6,7,8,9,10,11,12', 'Trish Loeblein,Kathy Perkins,Sam Reid (developer),Interviewer: Danielle Harlow', 'Run Now!,Download,Embed', '2015-04-13 22:25:17'),
(50, 'Fourier: Making Waves', 'Learn how to make waves of all different shapes by adding up sines or cosines. Make waves in space and time and measure their wavelengths and periods. See how changing the amplitudes of different harmonics changes the waves. Compare different mathematical expressions for your waves.', 'https://phet.colorado.edu/en/simulation/fourier', 'https://phet.colorado.edu/sims/fourier/fourier-thumbnail.png', 'Physics-Sound & Waves,Physics-Quantum Phenomena,Physics-Light & Radiation,Chemistry-Quantum Chemistry,Math', '9,10,11,12', 'Chris Malley (developer),Sam McKagan (lead),Carl Wieman,Interviewer: Danielle Harlow,Interviewer: Sam McKagan', 'Run Now!,Download,Embed', '2015-04-13 22:25:18'),
(51, 'Fraction Matcher', 'Match shapes and numbers to earn stars in this fractions game. Challenge yourself on any level you like. Try to collect lots of stars!', 'https://phet.colorado.edu/en/simulation/fraction-matcher', 'https://phet.colorado.edu/sims/fractions/fraction-matcher-thumbnail.png', 'Math', '1,2,3,4,5,6,7,8,9,10,11,12,k', 'Ariel Paul (lead designer),Sam Reid (developer),Kathy Perkins,Trish Loeblein,Mike Dubson,Noah Podolefsky', 'iPad/Tablet,Chromebook,Run Now!,Download,Embed,Run in HTML5', '2015-04-13 22:25:18'),
(52, 'Fractions Intro', 'Explore fractions while you help yourself to 1/3 of a chocolate cake and wash it down with 1/2 a glass of orange juice! Create your own fractions using fun interactive objects. Match shapes and numbers to earn stars in the fractions games. Challenge yourself on any level you like. Try to collect lots of stars!', 'https://phet.colorado.edu/en/simulation/fractions-intro', 'https://phet.colorado.edu/sims/fractions/fractions-intro-thumbnail.png', 'Math', '1,2,3,4,5,6,7,8,9,10,11,12,k', 'Ariel Paul (lead designer),Sam Reid (lead developer),Kathy Perkins,Trish Loeblein,Mike Dubson', 'Run Now!,Download,Embed', '2015-04-13 22:25:18'),
(53, 'Friction', 'Learn how friction causes a material to heat up and melt. Rub two objects together and they heat up. When one reaches the melting temperature, particles break free as the material melts away.', 'https://phet.colorado.edu/en/simulation/friction', 'https://phet.colorado.edu/sims/friction/friction-thumbnail.jpg', 'Physics-Motion,Physics-Heat & Thermo', '1,2,3,4,5,6,7,8,9,10,11,12,k', 'Michael Dubson (developer/lead),Carl Wieman,Interviewer: Wendy Adams,Interviewer: Mindy Gratny,Interviewer: Danielle Harlow', 'iPad/Tablet,Chromebook,Download,Embed,Run in HTML5,Run Now!', '2015-04-13 22:25:18'),
(54, 'Gas Properties', 'Pump gas molecules to a box and see what happens as you change the volume, add or remove heat, change gravity, and more. Measure the temperature and pressure, and discover how the properties of the gas vary in relation to each other.', 'https://phet.colorado.edu/en/simulation/gas-properties', 'https://phet.colorado.edu/sims/ideal-gas/gas-properties-thumbnail.png', 'Physics-Work, Energy & Power,Physics-Heat & Thermo,Chemistry-General Chemistry,Earth Science', '1,2,3,4,5,6,7,8,9,10,11,12,k', 'Jack Barbera,Michael Dubson,Linda Koch,Ron LeMaster (developer),Kathy Perkins,Carl Wieman,Interviewer: Danielle Harlow', 'Run Now!,Download,Embed', '2015-04-13 22:25:19'),
(55, 'Gene Expression - The Basics', 'Express yourself through your genes! See if you can generate and collect three types of protein, then move on to explore the factors that affect protein synthesis in a cell.', 'https://phet.colorado.edu/en/simulation/gene-expression-basics', 'https://phet.colorado.edu/sims/gene-expression-basics/gene-expression-basics-thumbnail.png', 'Biology', '9,10,11,12', 'John Blanco (design and software development),Mike Klymkowsky,Kathy Perkins,Ariel Paul (design and interviews),Tom Perkins,George Emanuel (multi-cell model software)', 'Run Now!,Download,Embed', '2015-04-13 22:25:19'),
(56, 'Gene Machine: The Lac Operon', 'Build a gene network! The lac operon is a set of genes which are responsible for the metabolism of lactose in some bacterial cells. Explore the effects of mutations within the lac operon by adding or removing genes from the DNA.', 'https://phet.colorado.edu/en/simulation/gene-machine-lac-operon', 'https://phet.colorado.edu/sims/gene-network/gene-machine-lac-operon-thumbnail.png', 'Biology', '9,10,11,12', 'John Blanco (developer),Kathy Perkins,Noah Podolefsky,George Spiegelman,Jared Taylor', 'Run Now!,Download,Embed', '2015-04-13 22:25:19'),
(57, 'Generator', 'Generate electricity with a bar magnet! Discover the physics behind the phenomena by exploring magnets and how you can use them to make a bulb light.', 'https://phet.colorado.edu/en/simulation/generator', 'https://phet.colorado.edu/sims/faraday/generator-thumbnail.png', 'Physics-Work, Energy & Power,Physics-Electricity, Magnets & Circuits', '1,2,3,4,5,6,7,8,9,10,11,12,k', 'Michael Dubson,Chris Malley (developer),Kathy Perkins,Carl Wieman,Interviewer: Danielle Harlow,Interviewer: Archie Paulson', 'Run Now!,Download,Embed', '2015-04-13 22:25:20'),
(58, 'Geometric Optics', 'How does a lens form an image? See how light rays are refracted by a lens. Watch how the image changes when you adjust the focal length of the lens, move the object, move the lens, or move the screen.', 'https://phet.colorado.edu/en/simulation/geometric-optics', 'https://phet.colorado.edu/sims/geometric-optics/geometric-optics-thumbnail.jpg', 'Physics-Light & Radiation', '6,7,8,9,10,11,12', 'Michael Dubson (developer/lead),Kathy Perkins,Interviewer: Mindy Gratny,Interviewer: Danielle Harlow', 'Chromebook,Download,Embed,Run Now!', '2015-04-13 22:25:20'),
(59, 'Glaciers', 'Adjust mountain snowfall and temperature to see the glacier grow and shrink. Use scientific tools to measure thickness, velocity and glacial budget.', 'https://phet.colorado.edu/en/simulation/glaciers', 'https://phet.colorado.edu/sims/glaciers/glaciers-thumbnail.png', 'Earth Science', '1,2,3,4,5,6,7,8,9,10,11,12,k', 'Wendy Adams,Bob Anderson,Andrea Blair,Chris Malley (developer),Archie Paulson (lead),Kathy Perkins,Dylan Ward', 'Run Now!,Download,Embed', '2015-04-13 22:25:20'),
(60, 'Graphing Lines', 'Explore the world of lines. Investigate the relationships between linear equations, slope, and graphs of lines. Challenge yourself in the line game!', 'https://phet.colorado.edu/en/simulation/graphing-lines', 'https://phet.colorado.edu/sims/line-graphing/graphing-lines-thumbnail.png', 'Math', '6,7,8,9,10,11,12', 'Ariel Paul (lead),Chris Malley (developer),Bryce Gruneich,Karina Hensberry,Patricia Loeblein,Amanda McGarry,Kathy Perkins', 'iPad/Tablet,Chromebook,Run Now!,Download,Embed,Run in HTML5', '2015-04-13 22:25:21'),
(61, 'Gravity and Orbits', 'Move the sun, earth, moon and space station to see how it affects their gravitational forces and orbital paths. Visualize the sizes and distances between different heavenly bodies, and turn off gravity to see what would happen without it!', 'https://phet.colorado.edu/en/simulation/gravity-and-orbits', 'https://phet.colorado.edu/sims/gravity-and-orbits/gravity-and-orbits-thumbnail.png', 'Physics-Motion,Earth Science', '1,2,3,4,5,6,7,8,9,10,11,12,k', 'Noah Podolefsky (lead designer),Emily Moore (lead),Kathy Perkins,Trish Loeblein,Sam Reid (lead developer),Jon Olson (developer),Chris Malley (developer),John Blanco (developer)', 'Run Now!,Download,Embed', '2015-04-13 22:25:21'),
(62, 'Gravity Force Lab', 'Visualize the gravitational force that two objects exert on each other. Change properties of the objects in order to see how it changes the gravity force.', 'https://phet.colorado.edu/en/simulation/gravity-force-lab', 'https://phet.colorado.edu/sims/force-law-lab/gravity-force-lab-thumbnail.png', 'Physics-Motion', '1,2,3,4,5,6,7,8,9,10,11,12,k', 'Sam Reid,Noah Podolefsky,Carl Wieman,Trish Loeblein', 'iPad/Tablet,Chromebook,Run Now!,Download,Embed,Run in HTML5', '2015-04-13 22:25:21'),
(63, 'The Greenhouse Effect', 'How do greenhouse gases affect the climate? Explore the atmosphere during the ice age and today. What happens when you add clouds? Change the greenhouse gas concentration and see how the temperature changes. Then compare to the effect of glass panes. Zoom in and see how light interacts with molecules. Do all atmospheric gases contribute to the greenhouse effect?', 'https://phet.colorado.edu/en/simulation/greenhouse', 'https://phet.colorado.edu/sims/greenhouse/greenhouse-thumbnail.png', 'Physics-Heat & Thermo,Physics-Light & Radiation,Chemistry-General Chemistry,Earth Science', '1,2,3,4,5,6,7,8,9,10,11,12,k', 'Wendy Adams,John Blanco (developer),Kelly Lancaster,Ron LeMaster (developer),Trish Loeblein,Robert Parson,Kathy Perkins,Carl Wieman,Interviewer: Wendy Adams,Interviewer: Danielle Harlow,Interviewer: Kelly Lancaster', 'Run Now!,Download,Embed', '2015-04-13 22:25:22'),
(64, 'Isotopes and Atomic Mass', 'Are all atoms of an element the same? How can you tell one isotope from another? Use the sim to learn about isotopes and how abundance relates to the average atomic mass of an element.', 'https://phet.colorado.edu/en/simulation/isotopes-and-atomic-mass', 'https://phet.colorado.edu/sims/build-an-atom/isotopes-and-atomic-mass-thumbnail.png', 'Chemistry-General Chemistry', '6,7,8,9,10,11,12', 'Kelly Lancaster (lead),John Blanco (lead developer),Sam Reid (developer),Trish Loeblein,Emily Moore,Robert Parson,Kathy Perkins', 'Run Now!,Download,Embed', '2015-04-13 22:25:22'),
(65, 'John Travoltage', 'Make sparks fly with John Travoltage. Wiggle Johnnie''s foot and he picks up charges from the carpet. Bring his hand close to the door knob and get rid of the excess charge.', 'https://phet.colorado.edu/en/simulation/travoltage', 'https://phet.colorado.edu/sims/travoltage/travoltage-thumbnail.png', 'Physics-Electricity, Magnets & Circuits', '1,2,3,4,5,6,7,8,9,10,11,12,k', 'Sam Reid (developer),Carl Wieman,Interviewer: Wendy Adams', 'iPad/Tablet,Chromebook,Run Now!,Download,Embed,Run in HTML5', '2015-04-13 22:25:22'),
(66, 'Ladybug Motion 2D', 'Learn about position, velocity and acceleration vectors. Move the ladybug by setting the position, velocity or acceleration, and see how the vectors change. Choose linear, circular or elliptical motion, and record and playback the motion to analyze the behavior.', 'https://phet.colorado.edu/en/simulation/ladybug-motion-2d', 'https://phet.colorado.edu/sims/ladybug-motion-2d/ladybug-motion-2d-thumbnail.png', 'Physics-Motion', '1,2,3,4,5,6,7,8,9,10,11,12,k', 'Noah Podolefsky,Sam Reid,Trish Loeblein,Wendy Adams', 'Run Now!,Download,Embed', '2015-04-13 22:25:22'),
(67, 'Ladybug Revolution', 'Join the ladybug in an exploration of rotational motion. Rotate the merry-go-round to change its angle, or choose a constant angular velocity or angular acceleration. Explore how circular motion relates to the bug''s x,y position, velocity, and acceleration using vectors or graphs.', 'https://phet.colorado.edu/en/simulation/rotation', 'https://phet.colorado.edu/sims/rotation/rotation-thumbnail.png', 'Physics-Motion,Math', '6,7,8,9,10,11,12', 'Kathy Perkins,Wendy Adams,Mindy Gratny,Sam Reid', 'Run Now!,Download,Embed', '2015-04-13 22:25:23'),
(68, 'Lasers', 'Create a laser by pumping the chamber with a photon beam. Manage the energy states of the laser''s atoms to control its output.', 'https://phet.colorado.edu/en/simulation/lasers', 'https://phet.colorado.edu/sims/lasers/lasers-thumbnail.png', 'Physics-Quantum Phenomena,Physics-Light & Radiation,Chemistry-Quantum Chemistry', '6,7,8,9,10,11,12', 'Ron LeMaster (developer),Sam McKagan,Kathy Perkins,Carl Wieman,Interviewer: Danielle Harlow', 'Run Now!,Download,Embed', '2015-04-13 22:25:23'),
(69, 'Least-Squares Regression', 'Create your own scatter plot or use real-world data and try to fit a line to it! Explore how individual data points affect the correlation coefficient and best-fit line.', 'https://phet.colorado.edu/en/simulation/least-squares-regression', 'https://phet.colorado.edu/sims/html/least-squares-regression/1.0.0/least-squares-regression-128.png', 'Math', '9,10,11,12', 'Amanda McGarry (lead),Martin Veillette (developer),Patricia Loeblein,Ariel Paul,Kathy Perkins', 'iPad/Tablet,Chromebook,Run Now!,Download,Embed', '2015-04-13 22:25:23'),
(70, 'Lunar Lander', 'Can you avoid the boulder field and land safely, just before your fuel runs out, as Neil Armstrong did in 1969? Our version of this classic video game accurately simulates the real motion of the lunar lander with the correct mass, thrust, fuel consumption rate, and lunar gravity. The real lunar lander is very hard to control.', 'https://phet.colorado.edu/en/simulation/lunar-lander', 'https://phet.colorado.edu/sims/lunar-lander/lunar-lander-thumbnail.jpg', 'Physics-Motion', '1,2,3,4,5,6,7,8,9,10,11,12,k', 'Michael Dubson (developer/lead)', 'Chromebook,Download,Embed,Run Now!', '2015-04-13 22:25:23'),
(71, 'Magnet and Compass', 'Ever wonder how a compass worked to point you to the Arctic? Explore the interactions between a compass and bar magnet, and then add the earth and find the surprising answer! Vary the magnet''s strength, and see how things change both inside and outside. Use the field meter to measure how the magnetic field changes.', 'https://phet.colorado.edu/en/simulation/magnet-and-compass', 'https://phet.colorado.edu/sims/faraday/magnet-and-compass-thumbnail.png', 'Physics-Electricity, Magnets & Circuits', '1,2,3,4,5,6,7,8,9,10,11,12,k', 'Michael Dubson,Chris Malley (developer),Kathy Perkins,Carl Wieman,Interviewer: Danielle Harlow,Interviewer: Archie Paulson', 'Run Now!,Download,Embed', '2015-04-13 22:25:24'),
(72, 'Magnets and Electromagnets', 'Explore the interactions between a compass and bar magnet. Discover how you can use a battery and wire to make a magnet! Can you make it a stronger magnet? Can you make the magnetic field reverse?', 'https://phet.colorado.edu/en/simulation/magnets-and-electromagnets', 'https://phet.colorado.edu/sims/faraday/magnets-and-electromagnets-thumbnail.png', 'Physics-Electricity, Magnets & Circuits', '1,2,3,4,5,6,7,8,9,10,11,12,k', 'Michael Dubson,Chris Malley (developer),Kathy Perkins,Carl Wieman,Interviewer: Danielle Harlow,Interviewer: Archie Paulson', 'Run Now!,Download,Embed', '2015-04-13 22:25:24'),
(73, 'Masses & Springs', 'A realistic mass and spring laboratory. Hang masses from springs and adjust the spring stiffness and damping. You can even slow time. Transport the lab to different planets. A chart shows the kinetic, potential, and thermal energy for each spring.', 'https://phet.colorado.edu/en/simulation/mass-spring-lab', 'https://phet.colorado.edu/sims/mass-spring-lab/mass-spring-lab-thumbnail.jpg', 'Physics-Motion,Physics-Work, Energy & Power,Math', '1,2,3,4,5,6,7,8,9,10,11,12,k', 'Michael Dubson (developer/lead),Kathy Perkins,Interviewer: Wendy Adams', 'Chromebook,Download,Embed,Run Now!', '2015-04-13 22:25:24'),
(74, 'Maze Game', 'Learn about position, velocity, and acceleration in the "Arena of Pain". Use the green arrow to move the ball. Add more walls to the arena to make the game more difficult. Try to make a goal as fast as you can.', 'https://phet.colorado.edu/en/simulation/maze-game', 'https://phet.colorado.edu/sims/maze-game/maze-game-thumbnail.png', 'Physics-Motion', '1,2,3,4,5,6,7,8,9,10,11,12,k', 'Michael Dubson (developer/lead),Sam Reid (developer),Interviewer: Wendy Adams,Interviewer: Mindy Gratny', 'Run Now!,Download,Embed', '2015-04-13 22:25:24'),
(75, 'Membrane Channels', 'Insert channels in a membrane and see what happens. See how different types of channels allow particles to move through the membrane.', 'https://phet.colorado.edu/en/simulation/membrane-channels', 'https://phet.colorado.edu/sims/membrane-channels/membrane-channels-thumbnail.png', 'Biology', '6,7,8,9,10,11,12', 'John Blanco (developer),Noah Podolefsky (Lead),Katherine Perkins', 'Run Now!,Download,Embed', '2015-04-13 22:25:24'),
(76, 'Microwaves', 'How do microwaves heat up your coffee? Adjust the frequency and amplitude of microwaves. Watch water molecules rotating and bouncing around. View the microwave field as a wave, a single line of vectors, or the entire field.', 'https://phet.colorado.edu/en/simulation/microwaves', 'https://phet.colorado.edu/sims/microwaves/microwaves-thumbnail.png', 'Physics-Sound & Waves,Physics-Heat & Thermo,Physics-Light & Radiation,Chemistry-General Chemistry', '6,7,8,9,10,11,12', 'Wendy Adams,Ron LeMaster (developer),Kathy Perkins,Carl Wieman,Interviewer: Wendy Adams', 'Run Now!,Download,Embed', '2015-04-13 22:25:25'),
(77, 'Models of the Hydrogen Atom', 'How did scientists figure out the structure of atoms without looking at them? Try out different models by shooting light at the atom. Check how the prediction of the model matches the experimental results.', 'https://phet.colorado.edu/en/simulation/hydrogen-atom', 'https://phet.colorado.edu/sims/hydrogen-atom/hydrogen-atom-thumbnail.png', 'Physics-Quantum Phenomena,Physics-Light & Radiation,Chemistry-General Chemistry,Chemistry-Quantum Chemistry', '9,10,11,12', 'Wendy Adams,Michael Dubson,Chris Malley (developer),Sam McKagan (lead),Kathy Perkins,Carl Wieman,Interviewer: Mindy Gratny,Interviewer: Sam McKagan', 'Run Now!,Download,Embed', '2015-04-13 22:25:25'),
(78, 'Molarity', 'What determines the concentration of a solution? Learn about the relationships between moles, liters, and molarity by adjusting the amount of solute and solution volume. Change solutes to compare different chemical compounds in water.', 'https://phet.colorado.edu/en/simulation/molarity', 'https://phet.colorado.edu/sims/molarity/molarity-thumbnail.png', 'Chemistry-General Chemistry', '9,10,11,12', 'Julia Chamberlain (lead),Chris Malley (developer),Kelly Lancaster,Robert Parson,Kathy Perkins', 'iPad/Tablet,Chromebook,Run Now!,Download,Embed,Run in HTML5', '2015-04-13 22:25:25'),
(79, 'Molecular Motors', 'Discover what controls how fast tiny molecular motors in our body pull through a single strand of DNA. How hard can the motor pull in a tug of war with the optical tweezers? Discover what helps it pull harder. Do all molecular motors behave the same?', 'https://phet.colorado.edu/en/simulation/molecular-motors', 'https://phet.colorado.edu/sims/optical-tweezers/molecular-motors-thumbnail.png', 'Physics-Light & Radiation,Biology', '', 'Kathy Perkins,Chris Malley,Tom Perkins,Mike Dubson,Wendy Adams,Meredith Betterton', 'Run Now!,Download,Embed', '2015-04-13 22:25:25'),
(80, 'Molecule Polarity', 'When is a molecule polar? Change the electronegativity of atoms in a molecule to see how it affects polarity. See how the molecule behaves in an electric field. Change the bond angle to see how shape affects polarity. See how it works for real molecules in 3D.', 'https://phet.colorado.edu/en/simulation/molecule-polarity', 'https://phet.colorado.edu/sims/molecule-polarity/molecule-polarity-thumbnail.png', 'Biology,Chemistry-General Chemistry', '9,10,11,12', 'Kelly Lancaster (lead),Chris Malley (developer),Julia Chamberlain,Emily Moore,Robert Parson,Kathy Perkins', 'Run Now!,Download,Embed', '2015-04-13 22:25:26'),
(81, 'Molecules and Light', 'Do you ever wonder how a greenhouse gas affects the climate, or why the ozone layer is important? Use the sim to explore how light interacts with molecules in our atmosphere.', 'https://phet.colorado.edu/en/simulation/molecules-and-light', 'https://phet.colorado.edu/sims/molecules-and-light/molecules-and-light-thumbnail.png', 'Physics-Light & Radiation,Chemistry-General Chemistry,Earth Science', '6,7,8,9,10,11,12', 'John Blanco (developer),Kelly Lancaster (lead),Trish Loeblein,Robert Parson,Kathy Perkins', 'Run Now!,Download,Embed,Run in HTML5', '2015-04-13 22:25:26');
INSERT INTO `education` (`id`, `title`, `description`, `lesson_link`, `lesson_image`, `category`, `student_grades`, `author`, `content_type`, `time_scraped`) VALUES
(82, 'Molecule Shapes', 'Explore molecule shapes by building molecules in 3D! How does molecule shape change with different numbers of bonds and electron pairs? Find out by adding single, double or triple bonds and lone pairs to the central atom. Then, compare the model to real molecules!', 'https://phet.colorado.edu/en/simulation/molecule-shapes', 'https://phet.colorado.edu/sims/molecule-shapes/molecule-shapes-thumbnail.png', 'Chemistry-General Chemistry', '9,10,11,12', 'Emily Moore (Lead),Jonathan Olson (Developer),Kelly Lancaster,Julia Chamberlain,Kathy Perkins', 'iPad/Tablet,Chromebook,Run Now!,Download,Embed,Run in HTML5', '2015-04-13 22:25:26'),
(83, 'Molecule Shapes: Basics', 'Explore molecule shapes by building molecules in 3D! Find out how a molecule''s shape changes as you add atoms to a molecule.', 'https://phet.colorado.edu/en/simulation/molecule-shapes-basics', 'https://phet.colorado.edu/sims/molecule-shapes/molecule-shapes-basics-thumbnail.png', 'Chemistry-General Chemistry', '6,7,8,9,10,11,12', 'Emily Moore (Lead),Jonathan Olson (Developer),Kelly Lancaster,Julia Chamberlain,Kathy Perkins', 'iPad/Tablet,Chromebook,Run Now!,Download,Embed,Run in HTML5', '2015-04-13 22:25:27'),
(84, 'Motion in 2D', 'Try the new "Ladybug Motion 2D" simulation for the latest updated version. Learn about position, velocity, and acceleration vectors. Move the ball with the mouse or let the simulation move the ball in four types of motion (2 types of linear, simple harmonic, circle).', 'https://phet.colorado.edu/en/simulation/motion-2d', 'https://phet.colorado.edu/sims/motion-2d/motion-2d-thumbnail.png', 'Physics-Motion', '6,7,8,9,10,11,12', 'Michael Dubson (developer/lead),Sam Reid (developer)', 'Run Now!,Download,Embed', '2015-04-13 22:25:27'),
(85, 'The Moving Man', 'Learn about position, velocity, and acceleration graphs. Move the little man back and forth with the mouse and plot his motion. Set the position, velocity, or acceleration and let the simulation move the man for you.', 'https://phet.colorado.edu/en/simulation/moving-man', 'https://phet.colorado.edu/sims/moving-man/moving-man-thumbnail.png', 'Physics-Motion,Math', '1,2,3,4,5,6,7,8,9,10,11,12,k', 'Wendy Adams,Kathy Perkins,Sam Reid (developer),Carl Wieman,Interviewer: Danielle Harlow', 'Run Now!,Download,Embed', '2015-04-13 22:25:27'),
(86, 'My Solar System', 'Build your own system of heavenly bodies and watch the gravitational ballet. With this orbit simulator, you can set initial positions, velocities, and masses of 2, 3, or 4 bodies, and then see them orbit each other.', 'https://phet.colorado.edu/en/simulation/my-solar-system', 'https://phet.colorado.edu/sims/my-solar-system/my-solar-system-thumbnail.png', 'Physics-Motion,Physics-Work, Energy & Power,Earth Science', '9,10,11,12', 'Michael Dubson (developer/lead),Interviewer: Mindy Gratny,Interviewer: Danielle Harlow', 'Chromebook,Download,Embed,Run Now!', '2015-04-13 22:25:27'),
(87, 'Natural Selection', 'Explore natural selection by controlling the environment and causing mutations in bunnies.', 'https://phet.colorado.edu/en/simulation/natural-selection', 'https://phet.colorado.edu/sims/natural-selection/natural-selection-thumbnail.png', 'Biology', '1,2,3,4,5,6,7,8,k', 'Wendy Adams,Noah Podolefsky (lead),Jonathan Olson (developer)', 'Run Now!,Download,Embed', '2015-04-13 22:25:28'),
(88, 'Neon Lights & Other Discharge Lamps', 'Produce light by bombarding atoms with electrons. See how the characteristic spectra of different elements are produced, and configure your own element''s energy states to produce light of different colors.', 'https://phet.colorado.edu/en/simulation/discharge-lamps', 'https://phet.colorado.edu/sims/discharge-lamps/discharge-lamps-thumbnail.png', 'Physics-Quantum Phenomena,Physics-Light & Radiation,Chemistry-General Chemistry', '9,10,11,12', 'Ron LeMaster (developer),Sam McKagan,Kathy Perkins,Carl Wieman,Interviewer: Danielle Harlow,Interviewer: Sam McKagan', 'Run Now!,Download,Embed', '2015-04-13 22:25:28'),
(89, 'Neuron', 'Stimulate a neuron and monitor what happens. Pause, rewind, and move forward in time in order to observe the ions as they move across the neuron membrane.', 'https://phet.colorado.edu/en/simulation/neuron', 'https://phet.colorado.edu/sims/neuron/neuron-thumbnail.png', 'Biology', '9,10,11,12', 'Noah Podolefsky (Lead),Wendy Adams,Katherine Perkins,John Blanco (developer)', 'Run Now!,Download,Embed', '2015-04-13 22:25:28'),
(90, 'Normal Modes', 'Play with a 1D or 2D system of coupled mass-spring oscillators. Vary the number of masses, set the initial conditions, and watch the system evolve. See the spectrum of normal modes for arbitrary motion. See longitudinal or transverse modes in the 1D system.', 'https://phet.colorado.edu/en/simulation/normal-modes', 'https://phet.colorado.edu/sims/normal-modes/normal-modes-thumbnail.png', 'Physics-Motion,Physics-Sound & Waves', '', 'Michael Dubson (lead designer/developer),Jon Olson (developer),Ariel Paul (development/interviews),Trish Loeblein (development)', 'Chromebook,Download,Embed,Run Now!', '2015-04-13 22:25:28'),
(91, 'Nuclear Fission', 'Start a chain reaction, or introduce non-radioactive isotopes to prevent one. Control energy production in a nuclear reactor! (Previously part of the Nuclear Physics simulation - now there are separate Alpha Decay and Nuclear Fission sims.)', 'https://phet.colorado.edu/en/simulation/nuclear-fission', 'https://phet.colorado.edu/sims/nuclear-physics/nuclear-fission-thumbnail.png', 'Physics-Work, Energy & Power,Physics-Heat & Thermo,Physics-Quantum Phenomena,Physics-Light & Radiation,Chemistry-General Chemistry,Chemistry-Quantum Chemistry', '6,7,8,9,10,11,12', 'Wendy Adams,John Blanco (developer),Ron LeMaster (developer),Sam McKagan,Kathy Perkins,Noah Podolefsky,Carl Wieman,Interviewer: Wendy Adams,Interviewer: Danielle Harlow', 'Run Now!,Download,Embed', '2015-04-13 22:25:28'),
(92, 'Ohm''s Law', 'See how the equation form of Ohm''s law relates to a simple circuit. Adjust the voltage and resistance, and see the current change according to Ohm''s law. The sizes of the symbols in the equation change to match the circuit diagram.', 'https://phet.colorado.edu/en/simulation/ohms-law', 'https://phet.colorado.edu/sims/ohms-law/ohms-law-thumbnail.jpg', 'Physics-Electricity, Magnets & Circuits,Math', '6,7,8,9,10,11,12', 'Michael Dubson (developer/lead),Interviewer: Mindy Gratny', 'iPad/Tablet,Chromebook,Download,Embed,Run in HTML5,Run Now!', '2015-04-13 22:25:29'),
(93, 'Optical Quantum Control', 'Explore an active area of research in optical physics: producing designer pulse shapes to achieve specific purposes, such as breaking apart a molecule. Carefully create the perfect shaped pulse to break apart a molecule by individually manipulating the colors of light that make up a pulse.', 'https://phet.colorado.edu/en/simulation/optical-quantum-control', 'https://phet.colorado.edu/sims/optical-quantum-control/optical-quantum-control-thumbnail.png', '', '9,10,11,12', 'Chris Malley (developer),Sam McKagan (lead),Carl Wieman', 'Run Now!,Download,Embed', '2015-04-13 22:25:29'),
(94, 'Optical Tweezers and Applications', 'Did you ever imagine that you can use light to move a microscopic plastic bead? Explore the forces on the bead or slow time to see the interaction with the laser''s electric field. Use the optical tweezers to manipulate a single strand of DNA and explore the physics of tiny molecular motors. Can you get the DNA completely straight or stop the molecular motor?', 'https://phet.colorado.edu/en/simulation/optical-tweezers', 'https://phet.colorado.edu/sims/optical-tweezers/optical-tweezers-thumbnail.png', 'Physics-Sound & Waves,Physics-Light & Radiation,Biology', '', 'Wendy Adams,Michael Dubson,Chris Malley (developer),Kathy Perkins (lead),Thomas Perkins,Interviewer: Archie Paulson', 'Run Now!,Download,Embed', '2015-04-13 22:25:29'),
(95, 'Pendulum Lab', 'Play with one or two pendulums and discover how the period of a simple pendulum depends on the length of the string, the mass of the pendulum bob, and the amplitude of the swing. It''s easy to measure the period using the photogate timer. You can vary friction and the strength of gravity. Use the pendulum to find the value of g on planet X. Notice the anharmonic behavior at large amplitude.', 'https://phet.colorado.edu/en/simulation/pendulum-lab', 'https://phet.colorado.edu/sims/pendulum-lab/pendulum-lab-thumbnail.jpg', 'Physics-Motion,Math', '1,2,3,4,5,6,7,8,9,10,11,12,k', 'Michael Dubson (developer/lead),Trish Loeblein', 'Chromebook,Download,Embed,Run Now!', '2015-04-13 22:25:29'),
(96, 'Photoelectric Effect', 'See how light knocks electrons off a metal target, and recreate the experiment that spawned the field of quantum mechanics.', 'https://phet.colorado.edu/en/simulation/photoelectric', 'https://phet.colorado.edu/sims/photoelectric/photoelectric-thumbnail.png', 'Physics-Quantum Phenomena,Physics-Light & Radiation,Chemistry-General Chemistry,Chemistry-Quantum Chemistry', '9,10,11,12', 'Ron LeMaster (developer),Sam McKagan,Kathy Perkins,Carl Wieman,Interviewer: Danielle Harlow', 'Run Now!,Download,Embed', '2015-04-13 22:25:29'),
(97, 'pH Scale', 'Test the pH of things like coffee, spit, and soap to determine whether each is acidic, basic, or neutral. Visualize the relative number of hydroxide ions and hydronium ions in solution. Switch between logarithmic and linear scales. Investigate whether changing the volume or diluting with water affects the pH. Or you can design your own liquid!', 'https://phet.colorado.edu/en/simulation/ph-scale', 'https://phet.colorado.edu/sims/ph-scale/ph-scale-thumbnail.png', 'Biology,Chemistry-General Chemistry,Earth Science', '6,7,8,9,10,11,12', 'Wendy Adams,Jack Barbera,Laurie Langdon,Patricia Loeblein,Chris Malley (developer),Archie Paulson (lead),Kathy Perkins', 'iPad/Tablet,Chromebook,Run Now!,Download,Embed,Run in HTML5', '2015-04-13 22:25:30'),
(98, 'pH Scale: Basics', 'Test the pH of everyday liquids such as coffee, spit, and soap to determine whether each is acidic, basic, or neutral. Investigate how adding more of a liquid or diluting with water affects pH.', 'https://phet.colorado.edu/en/simulation/ph-scale-basics', 'https://phet.colorado.edu/sims/html/ph-scale-basics/1.1.1/ph-scale-basics-128.png', 'Chemistry-General Chemistry', '6,7,8', 'Yuen-ying Carpenter (lead),Chris Malley (developer),Emily B. Moore,Ariel Paul,Julia Chamberlain,Katherine Perkins,Patricia Loeblein,Sharon Siman-Tov (graphic arts)', 'iPad/Tablet,Chromebook,Run Now!,Download,Embed', '2015-04-13 22:25:30'),
(99, 'Plate Tectonics', 'Explore how plates move on the surface of the earth. Change temperature, composition, and thickness of plates. Discover how to create new mountains, volcanoes, or oceans!', 'https://phet.colorado.edu/en/simulation/plate-tectonics', 'https://phet.colorado.edu/sims/plate-tectonics/plate-tectonics-thumbnail.png', 'Earth Science', '6,7,8,9,10,11,12', 'Heather Houlton (lead designer),Noah Podolefsky (lead designer, interviewer),Jonathan Olson (developer),Kathy Perkins,Suzy Loper,Kevin Beals,Lauren Brodsky,Phaela Peck,Kat Quigley,Emily Moore (interviewer)', 'Run Now!,Download,Embed', '2015-04-13 22:25:30'),
(100, 'Plinko Probability', 'Play Plinko and develop your knowledge of statistics. Drops balls through a triangular grid of pegs and see the balls random walk through the lattice. Watch the histogram of final positions build up and approach the binomial distribution. Inspired by the Virtual Lab in Probability and Statistics at U. Alabama in Huntsville (www.math.uah.edu/stat)', 'https://phet.colorado.edu/en/simulation/plinko-probability', 'https://phet.colorado.edu/sims/plinko-probability/plinko-probability-thumbnail.jpg', 'Biology,Math', '6,7,8,9,10,11,12', 'Michael Dubson (developer/lead)', 'Chromebook,Download,Embed,Run Now!', '2015-04-13 22:25:31'),
(101, 'Projectile Motion', 'Blast a Buick out of a cannon! Learn about projectile motion by firing various objects. Set the angle, initial speed, and mass. Add air resistance. Make a game out of this simulation by trying to hit a target.', 'https://phet.colorado.edu/en/simulation/projectile-motion', 'https://phet.colorado.edu/sims/projectile-motion/projectile-motion-thumbnail.jpg', 'Physics-Motion,Math', '1,2,3,4,5,6,7,8,9,10,11,12,k', 'Michael Dubson (developer/lead),Interviewer: Wendy Adams', 'Chromebook,Download,Embed,Run Now!', '2015-04-13 22:25:31'),
(102, 'Quantum Bound States', 'Explore the properties of quantum "particles" bound in potential wells. See how the wave functions and probability densities that describe them evolve (or don''t evolve) over time.', 'https://phet.colorado.edu/en/simulation/bound-states', 'https://phet.colorado.edu/sims/bound-states/bound-states-thumbnail.png', 'Physics-Quantum Phenomena,Chemistry-Quantum Chemistry', '', 'Chris Malley (developer),Sam McKagan (lead),Kathy Perkins,Carl Wieman,Interviewer: Sam McKagan', 'Run Now!,Download,Embed', '2015-04-13 22:25:32'),
(103, 'Quantum Tunneling and Wave Packets', 'Watch quantum "particles" tunnel through barriers. Explore the properties of the wave functions that describe these particles.', 'https://phet.colorado.edu/en/simulation/quantum-tunneling', 'https://phet.colorado.edu/sims/quantum-tunneling/quantum-tunneling-thumbnail.png', 'Physics-Quantum Phenomena', '', 'Chris Malley (developer),Sam McKagan (lead),Kathy Perkins,Carl Wieman,Interviewer: Sam McKagan', 'Run Now!,Download,Embed', '2015-04-13 22:25:32'),
(104, 'Quantum Wave Interference', 'When do photons, electrons, and atoms behave like particles and when do they behave like waves? Watch waves spread out and interfere as they pass through a double slit, then get detected on a screen as tiny dots. Use quantum detectors to explore how measurements change the waves and the patterns they produce on the screen.', 'https://phet.colorado.edu/en/simulation/quantum-wave-interference', 'https://phet.colorado.edu/sims/quantum-wave-interference/quantum-wave-interference-thumbnail.png', 'Physics-Quantum Phenomena,Physics-Light & Radiation,Chemistry-Quantum Chemistry', '', 'Wendy Adams,Sam McKagan (lead),Kathy Perkins,Sam Reid (developer),Carl Wieman,Interviewer: Danielle Harlow,Interviewer: Sam McKagan', 'Run Now!,Download,Embed', '2015-04-13 22:25:32'),
(105, 'Radiating Charge', 'The electric field lines from a point charge evolve in time as the charge moves. Watch radiation propagate outward at the speed of light as you wiggle the charge. Stop a moving charge to see bremsstrahlung (braking) radiation. Explore the radiation patterns as the charge moves with sinusoidal, circular, or linear motion. You can move the charge any way you like, as long as you don’t exceed the speed of light.', 'https://phet.colorado.edu/en/simulation/radiating-charge', 'https://phet.colorado.edu/sims/radiating-charge/radiating-charge-thumbnail.png', 'Physics-Light & Radiation', '9,10,11,12', 'Michael Dubson (lead designer/developer),Ariel Paul (development/interviews)', 'Chromebook,Download,Embed,Run Now!', '2015-04-13 22:25:32'),
(106, 'Radioactive Dating Game', 'Learn about different types of radiometric dating, such as carbon dating. Understand how decay and half life work to enable radiometric dating. Play a game that tests your ability to match the percentage of the dating element that remains to the age of the object.', 'https://phet.colorado.edu/en/simulation/radioactive-dating-game', 'https://phet.colorado.edu/sims/nuclear-physics/radioactive-dating-game-thumbnail.png', 'Biology,Chemistry-General Chemistry,Earth Science', '6,7,8,9,10,11,12', 'Wendy Adams,John Blanco (developer),Kathy Perkins,Noah Podolefsky,Carl Wieman,Interviewer: Noah Podolefsky', 'Run Now!,Download,Embed', '2015-04-13 22:25:32'),
(107, 'Radio Waves & Electromagnetic Fields', 'Broadcast radio waves from KPhET. Wiggle the transmitter electron manually or have it oscillate automatically. Display the field as a curve or vectors. The strip chart shows the electron positions at the transmitter and at the receiver.', 'https://phet.colorado.edu/en/simulation/radio-waves', 'https://phet.colorado.edu/sims/radio-waves/radio-waves-thumbnail.png', 'Physics-Sound & Waves,Physics-Light & Radiation,Physics-Electricity, Magnets & Circuits,Chemistry-General Chemistry', '6,7,8,9,10,11,12', 'Wendy Adams,Michael Dubson,Ron LeMaster (developer),Kathy Perkins,Carl Wieman,Interviewer: Wendy Adams,Interviewer: Noah Podolefsky', 'Run Now!,Download,Embed', '2015-04-13 22:25:32'),
(108, 'The Ramp', 'Explore forces, energy and work as you push household objects up and down a ramp. Lower and raise the ramp to see how the angle of inclination affects the parallel forces acting on the file cabinet. Graphs show forces, energy and work.', 'https://phet.colorado.edu/en/simulation/the-ramp', 'https://phet.colorado.edu/sims/the-ramp/the-ramp-thumbnail.png', 'Physics-Motion,Physics-Work, Energy & Power', '9,10,11,12', 'Wendy Adams,Trish Loeblein,Kathy Perkins,Sam Reid (developer),Carl Wieman,Interviewer: Danielle Harlow', 'Run Now!,Download,Embed', '2015-04-13 22:25:33'),
(109, 'Ramp: Forces and Motion', 'Explore forces and motion as you push household objects up and down a ramp. Lower and raise the ramp to see how the angle of inclination affects the parallel forces. Graphs show forces, energy and work.', 'https://phet.colorado.edu/en/simulation/ramp-forces-and-motion', 'https://phet.colorado.edu/sims/motion-series/ramp-forces-and-motion-thumbnail.png', 'Physics-Motion', '6,7,8,9,10,11,12', 'Sam Reid (developer),Noah Podolefsky (lead design),Trish Loeblein,Kathy Perkins', 'Run Now!,Download,Embed', '2015-04-13 22:25:33'),
(110, 'Reactants, Products and Leftovers', 'Create your own sandwich and then see how many sandwiches you can make with different amounts of ingredients. Do the same with chemical reactions. See how many products you can make with different amounts of reactants. Play a game to test your understanding of reactants, products and leftovers. Can you get a perfect score on each level?', 'https://phet.colorado.edu/en/simulation/reactants-products-and-leftovers', 'https://phet.colorado.edu/sims/reactants-products-and-leftovers/reactants-products-and-leftovers-thumbnail.png', 'Chemistry-General Chemistry', '6,7,8,9,10,11,12', 'Kelly Lancaster (lead),Chris Malley (developer),Wendy Adams,Patricia Loeblein,Robert Parson,Kathy Perkins', 'iPad/Tablet,Chromebook,Run Now!,Download,Embed,Run in HTML5', '2015-04-13 22:25:33'),
(111, 'Reactions & Rates', 'Explore what makes a reaction happen by colliding atoms and molecules. Design experiments with different reactions, concentrations, and temperatures. When are reactions reversible? What affects the rate of a reaction?', 'https://phet.colorado.edu/en/simulation/reactions-and-rates', 'https://phet.colorado.edu/sims/reactions-and-rates/reactions-and-rates-thumbnail.png', 'Physics-Heat & Thermo,Biology,Chemistry-General Chemistry', '9,10,11,12', 'Linda Koch (lead),Ron LeMaster (developer),Trish Loeblein,Kathy Perkins,Interviewer: Mindy Gratny', 'Run Now!,Download,Embed', '2015-04-13 22:25:33'),
(112, 'Resistance in a Wire', 'Learn about the physics of resistance in a wire. Change its resistivity, length, and area to see how they affect the wire''s resistance. The sizes of the symbols in the equation change along with the diagram of a wire.', 'https://phet.colorado.edu/en/simulation/resistance-in-a-wire', 'https://phet.colorado.edu/sims/resistance-in-a-wire/resistance-in-a-wire-thumbnail.jpg', 'Physics-Electricity, Magnets & Circuits,Math', '6,7,8,9,10,11,12', 'Michael Dubson (developer/lead),Interviewer: Wendy Adams,Interviewer: Mindy Gratny', 'iPad/Tablet,Chromebook,Download,Embed,Run in HTML5,Run Now!', '2015-04-13 22:25:34'),
(113, 'Resonance', 'For advanced undergraduate students: Observe resonance in a collection of driven, damped harmonic oscillators. Vary the driving frequency and amplitude, the damping constant, and the mass and spring constant of each resonator. Notice the long-lived transients when damping is small, and observe the phase change for resonators above and below resonance.', 'https://phet.colorado.edu/en/simulation/resonance', 'https://phet.colorado.edu/sims/resonance/resonance-thumbnail.jpg', 'Physics-Motion', '9,10,11,12', 'Michael Dubson (lead design, lead developer),Patricia Loeblein (design),Jonathan Olson (developer),Kathy Perkins (design),Mindy Gratny (interviews)', 'Chromebook,Download,Embed,Run Now!', '2015-04-13 22:25:34'),
(114, 'Reversible Reactions', 'Watch a reaction proceed over time. How does total energy affect a reaction rate? Vary temperature, barrier height, and potential energies. Record concentrations and time in order to extract rate coefficients. Do temperature dependent studies to extract Arrhenius parameters. This simulation is best used with teacher guidance because it presents an analogy of chemical reactions.', 'https://phet.colorado.edu/en/simulation/reversible-reactions', 'https://phet.colorado.edu/sims/ideal-gas/reversible-reactions-thumbnail.png', 'Physics-Heat & Thermo,Chemistry-General Chemistry', '9,10,11,12', 'Jack Barbera,Linda Koch (lead),Ron LeMaster (developer),Interviewer: Wendy Adams', 'Run Now!,Download,Embed', '2015-04-13 22:25:34'),
(115, 'Rutherford Scattering', 'How did Rutherford figure out the structure of the atom without being able to see it? Simulate the famous experiment in which he disproved the Plum Pudding model of the atom by observing alpha particles bouncing off atoms and determining that they must have a small core.', 'https://phet.colorado.edu/en/simulation/rutherford-scattering', 'https://phet.colorado.edu/sims/rutherford-scattering/rutherford-scattering-thumbnail.png', 'Physics-Quantum Phenomena,Chemistry-General Chemistry', '9,10,11,12', 'Wendy Adams,Michael Dubson,Chris Malley (developer),Sam McKagan (lead),Kathy Perkins,Carl Wieman,Interviewer: Sam McKagan', 'Run Now!,Download,Embed', '2015-04-13 22:25:34'),
(116, 'Salts & Solubility', 'Add different salts to water, then watch them dissolve and achieve a dynamic equilibrium with solid precipitate. Compare the number of ions in solution for highly soluble NaCl to other slightly soluble salts. Relate the charges on ions to the number of ions in the formula of a salt. Calculate Ksp values.', 'https://phet.colorado.edu/en/simulation/soluble-salts', 'https://phet.colorado.edu/sims/soluble-salts/soluble-salts-thumbnail.png', 'Biology,Chemistry-General Chemistry', '1,2,3,4,5,6,7,8,9,10,11,12,k', 'Wendy Adams,Linda Koch (lead),Ron LeMaster (developer),Trish Loeblein,Kathy Perkins,Interviewer: Danielle Harlow,Interviewer: Linda Koch', 'Run Now!,Download,Embed', '2015-04-13 22:25:35'),
(117, 'Self-Driven Particle Model', 'Learn how simple rule-driven dynamical systems can produce complex dynamical behavior, like 2nd order phase transitions, criticality and clustering. This simulation will guide you through a tutorial that introduces the model incrementally and depicts the computation of the order parameter, critical parameter and critical exponent.', 'https://phet.colorado.edu/en/simulation/self-driven-particle-model', 'https://phet.colorado.edu/sims/self-driven-particle-model/self-driven-particle-model-thumbnail.png', '', '', 'Sam Reid (developer/lead)', 'Run Now!,Download,Embed', '2015-04-13 22:25:35'),
(118, 'Semiconductors', 'Dope the semiconductor to create a diode. Watch the electrons change position and energy.', 'https://phet.colorado.edu/en/simulation/semiconductor', 'https://phet.colorado.edu/sims/semiconductor/semiconductor-thumbnail.png', 'Physics-Quantum Phenomena,Physics-Electricity, Magnets & Circuits,Chemistry-Quantum Chemistry', '', 'Sam McKagan,Kathy Perkins,Sam Reid (developer),Carl Wieman,Interviewer: Wendy Adams', 'Run Now!,Download,Embed', '2015-04-13 22:25:35'),
(119, 'Signal Circuit', 'Why do the lights turn on in a room as soon as you flip a switch? Flip the switch and watch the electrons. Does the light turn on immediately? Explain using your observations of the model.', 'https://phet.colorado.edu/en/simulation/signal-circuit', 'https://phet.colorado.edu/sims/signal-circuit/signal-circuit-thumbnail.png', 'Physics-Electricity, Magnets & Circuits', '1,2,3,4,5,6,7,8,9,10,11,12,k', 'Sam Reid (developer),Carl Wieman,Interviewer: Wendy Adams', 'Run Now!,Download,Embed', '2015-04-13 22:25:35'),
(120, 'Simplified MRI', 'Is it a tumor? Magnetic Resonance Imaging (MRI) can tell. Your head is full of tiny radio transmitters (the nuclear spins of the hydrogen nuclei of your water molecules). In an MRI unit, these little radios can be made to broadcast their positions, giving a detailed picture of the inside of your head.', 'https://phet.colorado.edu/en/simulation/mri', 'https://phet.colorado.edu/sims/mri/mri-thumbnail.png', 'Physics-Quantum Phenomena,Physics-Light & Radiation,Biology,Chemistry-Quantum Chemistry', '9,10,11,12', 'Michael Dubson,Ron LeMaster (developer),Sam McKagan,Kathy Perkins,Carl Wieman,Interviewer: Danielle Harlow', 'Run Now!,Download,Embed', '2015-04-13 22:25:36'),
(121, 'Sound', 'This simulation lets you see sound waves. Adjust the frequency or volume and you can see and hear how the wave changes. Move the listener around and hear what she hears.', 'https://phet.colorado.edu/en/simulation/sound', 'https://phet.colorado.edu/sims/sound/sound-thumbnail.png', 'Physics-Sound & Waves,Biology,Earth Science', '1,2,3,4,5,6,7,8,9,10,11,12,k', 'Ron LeMaster (developer),Kathy Perkins,Carl Wieman,Interviewer: Wendy Adams,Interviewer: Danielle Harlow', 'Run Now!,Download,Embed', '2015-04-13 22:25:36'),
(122, 'States of Matter', 'Watch different types of molecules form a solid, liquid, or gas. Add or remove heat and watch the phase change. Change the temperature or volume of a container and see a pressure-temperature diagram respond in real time. Relate the interaction potential to the forces between molecules.', 'https://phet.colorado.edu/en/simulation/states-of-matter', 'https://phet.colorado.edu/sims/states-of-matter/states-of-matter-thumbnail.png', 'Physics-Work, Energy & Power,Physics-Heat & Thermo,Chemistry-General Chemistry', '1,2,3,4,5,9,10,11,12,k', 'Wendy Adams,Paul Beale,John Blanco (developer),Sarah McKagan,Kathy Perkins,Noah Podolefsky,Trish Loeblein', 'Run Now!,Download,Embed', '2015-04-13 22:25:36'),
(123, 'States of Matter: Basics', 'Heat, cool and compress atoms and molecules and watch as they change between solid, liquid and gas phases.', 'https://phet.colorado.edu/en/simulation/states-of-matter-basics', 'https://phet.colorado.edu/sims/states-of-matter/states-of-matter-basics-thumbnail.png', 'Physics-Heat & Thermo,Chemistry-General Chemistry', '1,2,3,4,5,6,7,8,k', 'Wendy Adams,Paul Beale,John Blanco (developer),Sarah McKagan,Emily Moore,Kathy Perkins,Noah Podolefsky,Trish Loeblein', 'Run Now!,Download,Embed', '2015-04-13 22:25:36'),
(124, 'Stern-Gerlach Experiment', 'The classic Stern-Gerlach Experiment shows that atoms have a property called spin. Spin is a kind of intrinsic angular momentum, which has no classical counterpart. When the z-component of the spin is measured, one always gets one of two values: spin up or spin down.', 'https://phet.colorado.edu/en/simulation/stern-gerlach', 'https://phet.colorado.edu/sims/stern-gerlach/stern-gerlach-thumbnail.jpg', 'Physics-Quantum Phenomena,Chemistry-Quantum Chemistry', '', 'Michael Dubson (developer/lead),Sam McKagan (co-lead),Carl Wieman,Interviewer: Sam McKagan', 'Chromebook,Download,Embed,Run Now!', '2015-04-13 22:25:37'),
(125, 'Stretching DNA', 'Explore stretching just a single strand of DNA using optical tweezers or fluid flow. Experiment with the forces involved and measure the relationship between the stretched DNA length and the force required to keep it stretched. Is DNA more like a rope or like a spring?', 'https://phet.colorado.edu/en/simulation/stretching-dna', 'https://phet.colorado.edu/sims/optical-tweezers/stretching-dna-thumbnail.png', 'Physics-Light & Radiation,Biology', '', 'Kathy Perkins,Chris Malley,Tom Perkins,Mike Dubson,Wendy Adams,Meredith Betterton', 'Run Now!,Download,Embed', '2015-04-13 22:25:37'),
(126, 'Sugar and Salt Solutions', 'What happens when sugar and salt are added to water? Pour in sugar, shake in salt, and evaporate water to see the effects on concentration and conductivity. Zoom in to see how different sugar and salt compounds dissolve. Zoom in again to explore the role of water.', 'https://phet.colorado.edu/en/simulation/sugar-and-salt-solutions', 'https://phet.colorado.edu/sims/sugar-and-salt-solutions/sugar-and-salt-solutions-thumbnail.png', 'Biology,Chemistry-General Chemistry', '1,2,3,4,5,6,7,8,9,10,11,12,k', 'Kelly Lancaster (lead),Sam Reid (developer),Emily Moore,Julia Chamberlain,Trish Loeblein,Robert Parson,Kathy Perkins', 'Run Now!,Download,Embed', '2015-04-13 22:25:37'),
(127, 'Torque', 'Investigate how torque causes an object to rotate. Discover the relationships between angular acceleration, moment of inertia, angular momentum and torque.', 'https://phet.colorado.edu/en/simulation/torque', 'https://phet.colorado.edu/sims/rotation/torque-thumbnail.png', 'Physics-Motion', '6,7,8,9,10,11,12', 'Wendy Adams,Sam Reid,Kathy Perkins,Trish Loeblein', 'Run Now!,Download,Embed', '2015-04-13 22:25:37'),
(128, 'Under Pressure', 'Explore pressure under and above water. See how pressure changes as you change fluids, gravity, container shapes, and volume.', 'https://phet.colorado.edu/en/simulation/under-pressure', 'https://phet.colorado.edu/sims/fluid-pressure-and-flow/under-pressure-thumbnail.png', 'Earth Science', '9,10,11,12', 'Sam Reid (lead designer/developer),Noah Podolefsky,Ariel Paul,Trish Loeblein,Kathy Perkins', 'iPad/Tablet,Chromebook,Run Now!,Download,Embed,Run in HTML5', '2015-04-13 22:25:37'),
(129, 'Vector Addition', 'Learn how to add vectors. Drag vectors onto a graph, change their length and angle, and sum them together. The magnitude, angle, and components of each vector can be displayed in several formats.', 'https://phet.colorado.edu/en/simulation/vector-addition', 'https://phet.colorado.edu/sims/vector-addition/vector-addition-thumbnail.jpg', 'Math', '6,7,8,9,10,11,12', 'Michael Dubson (developer/lead),Interviewer: Mindy Gratny', 'Chromebook,Download,Embed,Run Now!', '2015-04-13 22:25:38'),
(130, 'Wave Interference', 'Make waves with a dripping faucet, audio speaker, or laser! Add a second source or a pair of slits to create an interference pattern.', 'https://phet.colorado.edu/en/simulation/wave-interference', 'https://phet.colorado.edu/sims/wave-interference/wave-interference-thumbnail.png', 'Physics-Sound & Waves,Physics-Light & Radiation,Earth Science', '1,2,3,4,5,6,7,8,9,10,11,12,k', 'Wendy Adams,Noah Podolefsky (lead),Sam Reid (developer),Interviewer: Danielle Harlow,Interviewer: Noah Podolefsky', 'Run Now!,Download,Embed', '2015-04-13 22:25:38'),
(131, 'Wave on a String', 'Watch a string vibrate in slow motion. Wiggle the end of the string and make waves, or adjust the frequency and amplitude of an oscillator. Adjust the damping and tension. The end can be fixed, loose, or open.', 'https://phet.colorado.edu/en/simulation/wave-on-a-string', 'https://phet.colorado.edu/sims/wave-on-a-string/wave-on-a-string-thumbnail.png', 'Physics-Sound & Waves,Chemistry-General Chemistry,Earth Science', '1,2,3,4,5,6,7,8,9,10,11,12,k', 'Michael Dubson (developer/lead),Interviewer: Wendy Adams,Interviewer: Danielle Harlow', 'iPad/Tablet,Chromebook,Download,Embed,Run in HTML5,Run Now!', '2015-04-13 22:25:38');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
